# [OPTIONAL] AWS Environment
env:
  account: "xxxxxxxxxxxx"
  region: ap-northeast-1

# Project name
project: AutoStop

# Backend
#backend: s3://<bucket>/<key>

# Timezone
timezone: Asia/Tokyo

# Slack Webhook URL
slackWebhookUrl: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
